#                    ##        .
#              ## ## ##       ==
#           ## ## ## ##      ===
#       /""""""""""""""""___/ ===
#  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
#       \______ L          __/
#        \    \        __/
#          \____\______/
#
#  -- DOCKERFILE --
#
# IHMC UoE NON CAMERA LOGGER
FROM ubuntu:14.04
MAINTAINER Doug Stephen <dstephen@ihmc.us>

ENV INITRD No
ENV LOGGER_VERSION=0.7.3
ENV IHMC_LOGGER_IP=localhost

# RUN ln -sf /usr/share/zoneinfo/America/Chicago localtime
RUN ln -sf /usr/share/zoneinfo/Europe/London localtime
RUN locale-gen en_US.UTF-8

RUN DEBIAN_FRONTEND=noninteractive apt-get update -qqy \
	&& DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

# Get required base set of tools
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
	wget curl apt-utils nano openjdk-7-jre-headless apparmor-utils build-essential

RUN mkdir -p /root/.ihmc /root/robotLogs

ADD IHMCLogger-${LOGGER_VERSION}.tar /root/

RUN mv /root/IHMCLogger-${LOGGER_VERSION} /root/IHMCLogger

VOLUME ["/root/robotLogs"]

CMD ["/bin/bash", "-c", "/root/IHMCLogger/bin/IHMCLogger", "-n", "-d", "/root/robotLogs"]
# CMD ["-c", "/root/IHMCLogger/bin/IHMCLogger", "-n"]
